export default {
  login: 'willyanbertolino',
  id: 57110420,
  node_id: 'MDQ6VXNlcjU3MTEwNDIw',
  avatar_url: 'https://avatars.githubusercontent.com/u/57110420?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/willyanbertolino',
  html_url: 'https://github.com/willyanbertolino',
  followers_url: 'https://api.github.com/users/willyanbertolino/followers',
  following_url:
    'https://api.github.com/users/willyanbertolino/following{/other_user}',
  gists_url: 'https://api.github.com/users/willyanbertolino/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/willyanbertolino/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/willyanbertolino/subscriptions',
  organizations_url: 'https://api.github.com/users/willyanbertolino/orgs',
  repos_url: 'https://api.github.com/users/willyanbertolino/repos',
  events_url: 'https://api.github.com/users/willyanbertolino/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/willyanbertolino/received_events',
  type: 'User',
  site_admin: false,
  name: 'Willyan Henrique Pontim Bertolino',
  company: null,
  blog: '',
  location: 'Apucarana - PR - (Brazil)',
  email: null,
  hireable: null,
  bio: 'PhD in Physics and Web Developer - MERN stack',
  twitter_username: null,
  public_repos: 7,
  public_gists: 0,
  followers: 2,
  following: 3,
  created_at: '2019-10-28T18:12:08Z',
  updated_at: '2021-08-31T14:32:11Z',
};
