export default [
  {
    login: 'hacker8853',
    id: 76920935,
    node_id: 'MDQ6VXNlcjc2OTIwOTM1',
    avatar_url: 'https://avatars.githubusercontent.com/u/76920935?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hacker8853',
    html_url: 'https://github.com/hacker8853',
    followers_url: 'https://api.github.com/users/hacker8853/followers',
    following_url:
      'https://api.github.com/users/hacker8853/following{/other_user}',
    gists_url: 'https://api.github.com/users/hacker8853/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/hacker8853/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hacker8853/subscriptions',
    organizations_url: 'https://api.github.com/users/hacker8853/orgs',
    repos_url: 'https://api.github.com/users/hacker8853/repos',
    events_url: 'https://api.github.com/users/hacker8853/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/hacker8853/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'japoewn',
    id: 89349062,
    node_id: 'MDQ6VXNlcjg5MzQ5MDYy',
    avatar_url: 'https://avatars.githubusercontent.com/u/89349062?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/japoewn',
    html_url: 'https://github.com/japoewn',
    followers_url: 'https://api.github.com/users/japoewn/followers',
    following_url:
      'https://api.github.com/users/japoewn/following{/other_user}',
    gists_url: 'https://api.github.com/users/japoewn/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/japoewn/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/japoewn/subscriptions',
    organizations_url: 'https://api.github.com/users/japoewn/orgs',
    repos_url: 'https://api.github.com/users/japoewn/repos',
    events_url: 'https://api.github.com/users/japoewn/events{/privacy}',
    received_events_url: 'https://api.github.com/users/japoewn/received_events',
    type: 'User',
    site_admin: false,
  },
];
